### ISSUE TITLE
I got error with login

### ISSUE THREAD

**Issue by ThreadShakur** [Elipzer/SteamAuthenticatorPython#4]
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    h = hmac.new(base64.b32decode('<secretkey>'), v, hashlib.sha1)
  File "/usr/lib/python2.7/base64.py", line 205, in b32decode
    raise TypeError('Incorrect padding')
TypeError: Incorrect padding

where i can got this secret key?

**Comment by Elipzer** [comment]
You need to put the secret in the string.

**Comment by PlatinumDragon** [comment]
What is the secret and how to get it?
