### ISSUE TITLE
TypeError: Incorrect padding

### ISSUE THREAD

**Issue by coderofuniverse** [Elipzer/SteamAuthenticatorPython#5]
Trying to launch script and get
 `  h = hmac.new(base64.b32decode('<secretkey>'), v, hashlib.sha1)
  File "C:\Python27\lib\base64.py", line 205, in b32decode
    raise TypeError('Incorrect padding')
TypeError: Incorrect padding`

**Comment by Elipzer** [comment]
It looks like your secret key is not formatted correctly for base64.

**Comment by coderofuniverse** [comment]
oh, so Do I must put my secret key? I thought it do automatically

**Comment by Elipzer** [comment]
Yes
